{
  "config" : {
    "scriptInfo" : {
      "language" : "groovy",
      "script" : "// do nothing"
    }
  },
  "ignoreConfirmationMessage" : true,
  "name" : "CLAC-A-005 NOOP Form Bot",
  "botKey" : "platform-script-evaluation-bot",
  "key" : "cLACA005NOOPFormBot"
}